Upgrade setuptools for Python 3.7 and fix gevent
Fix issue with ValueError by upgrading setuptools (see PEP552)

    ValueError: bad marshal data (unknown type code)

Use conditionnal marker available in PEP426 (since pip version 6.0)

See: https://www.python.org/dev/peps/pep-0426/#compatible-release-comparisons-in-environment-markers